### ISSUE TITLE
Ehabitz verbeterpunten Webite

### ISSUE THREAD

**Issue by Thimovdb** [Thimovdb/Ehabitz#1]
PC
pages:	cases		Blog
* loram ipsum weghalen

mobile;
page: Home																		
* afbeeldingen bij slider verwijderen
* te veel tussen ruimte bij text
* resultaat gerichte opltimalisaties : staat niet netjes
* afbeeldingen klaten beoordeling te groot/ ovaal

page: over ons
* over ons afbeelding zelfdekant voor mobile

page: Team
* Team afbeeldingen

**Comment by ScottOverdrive** [comment]
- loram ipsum weghalen en vervangen met correcte text

**Comment by ScottOverdrive** [comment]
- afbeeldingen bij slider verwijderen (Gebruik bijv "Smush")

**Comment by ScottOverdrive** [comment]
mobile;
page: Home

- font-size: 30px;

**Comment by ScottOverdrive** [comment]
- size van image niet vernaggelen...

**Comment by ScottOverdrive** [comment]
- team updaten

**Comment by ScottOverdrive** [comment]
- engelse versie team naar realiteit maken
- engelse FAQ naar realiteit
- engelse blog beteren

**Comment by ScottOverdrive** [comment]
> Linken om spul af te jatten: https://www.adwise.nl/ en: https://teamnijhuis.com/nl/aanvraag-digitale-marketing-review/?gclid=CjwKCAjwt7PcBRBbEiwAfwfVGOEBZNANmzh5A30sAtTDk8Fy6jEF0KqqiYUZktDEmfiIjXZk9blelxoCZDgQAvD_BwE

**Comment by Thimovdb** [comment]
- boven aan site email to/ call to toevoegen voor mobile
